version: '3.9'
services:
  db:
    container_name: kong-db
    image: postgres:13
    pull_policy: if_not_present
    restart: always
    networks:
      - kong-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong123
      - POSTGRES_DB=kong
    
  kong:
    container_name: kong-gateway
    image: kong-image
    pull_policy: if_not_present
    restart: always
    depends_on:
      - db
    networks:
      - kong-network
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=db
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong123
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002

networks:
  kong-network:
    external: true