node('default-node') {
  environment {
    DOCKER_IMAGE = "yasinah22/user-img"
    IMAGE_TAG = "latest"
  }

  stage('Checkout') {
    git url: 'https://github.com/NetSinx/yconnect-shop', branch: 'master'
  }

  stage('Build') {
    docker.build("${DOCKER_IMAGE}:${IMAGE_TAG}")
  }

  stage('Deploy') {
    def app = docker.image("${DOCKER_IMAGE}:${IMAGE_TAG}")
    
    docker.withRegistry('', 'docker-reg') {
      app.push()
    }
  }

  post {
    cleanup {
      sh "docker rmi ${DOCKER_IMAGE}:${IMAGE_TAG}"
    }
  }
}