GET http://localhost:8086/api/auth/csrf-token
###
POST http://localhost:8086/api/auth/login
Content-Type: application/json
CSRF-Token: INFOuAlpAt0JlFgOChjrsyo5bBzUsHndKzJXk7nbvDU

{
    "email": "yasin@gmail.com",
    "password": "yasin123"
}